<?php

return [
    'default' => 'id_formal',

    'variants' => [
        'id_formal' => [
            'label' => 'Indonesia Formal',
            'carbon_locale' => 'id',
            'ui' => [
                'hero_kicker' => 'Undangan pernikahan',
                'guest_label_personal' => 'Kepada Yth.',
                'guest_label_general' => 'Undangan Umum',
                'guest_name_fallback' => 'Bapak/Ibu/Saudara/i',
                'guest_intro_personal' => 'Terima kasih telah menerima undangan personal ini. Merupakan kebahagiaan bagi kami apabila Anda berkenan hadir dan memberikan doa restu.',
                'guest_intro_general' => 'Silakan bagikan undangan umum ini kepada keluarga, sahabat, dan rekan yang relevan.',
                'status_label' => 'Status',
                'main_date_label' => 'Tanggal utama',
                'countdown_label' => 'Countdown menuju hari bahagia',
                'countdown_units' => ['Hari', 'Jam', 'Menit', 'Detik'],
                'couple_label' => 'Pasangan',
                'schedule_label' => 'Jadwal dan lokasi',
                'album_label' => 'Album',
                'rsvp_label' => 'RSVP',
                'rsvp_title' => 'Konfirmasi kehadiran Anda.',
                'rsvp_name_placeholder' => 'Nama Anda',
                'rsvp_phone_placeholder' => 'Nomor WhatsApp',
                'rsvp_message_placeholder' => 'Ucapan atau catatan',
                'rsvp_submit' => 'Kirim RSVP',
                'music_label' => 'Backsound',
                'music_title' => 'Putar suasana invitation.',
                'gift_label' => 'Gifting',
                'gift_title' => 'Pilihan hadiah untuk Anda.',
                'gift_confirm' => 'Konfirmasi hadiah',
                'comments_label' => 'Ucapan',
                'comments_title' => 'Tulis pesan terbaik untuk mempelai.',
                'comments_name_placeholder' => 'Nama',
                'comments_message_placeholder' => 'Tulis ucapan',
                'comments_submit' => 'Kirim ucapan',
                'comments_empty' => 'Belum ada ucapan yang ditampilkan.',
                'qr_label' => 'QR Check-in',
                'qr_title' => 'Siapkan akses tamu untuk hari-H.',
                'qr_note' => 'Payload QR tidak memuat data pribadi.',
                'closing_label' => 'Penutup',
                'closing_title' => 'Sampai bertemu di hari bahagia kami.',
                'map_button' => 'Buka Maps',
                'rsvp_status_labels' => [
                    'hadir' => 'Hadir',
                    'tidak_hadir' => 'Tidak hadir',
                    'ragu' => 'Ragu',
                ],
            ],
            'defaults' => [
                'opening_text' => 'Dengan memohon rahmat dan ridho Allah SWT, kami bermaksud menyelenggarakan acara pernikahan putra-putri kami.',
                'invitation_text' => 'Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir untuk memberikan doa restu.',
                'closing_text' => 'Atas kehadiran dan doa restu yang diberikan, kami mengucapkan terima kasih.',
                'no_gift_message' => 'Dengan segala kerendahan hati, kami tidak menerima kado dalam bentuk apa pun. Doa restu Anda sudah lebih dari cukup bagi kami.',
                'gift_instructions' => 'Doa restu merupakan hadiah terbaik. Jika berkenan, hadiah dapat dikirim melalui informasi berikut.',
                'broadcast_template' => "Assalamualaikum Wr. Wb.\n\nKepada Yth. {{guest_name}},\nDengan penuh rasa syukur kami mengundang Anda untuk hadir di acara pernikahan {{couple_names}} pada {{event_date}}.\n\nSilakan buka undangan melalui link berikut:\n{{invitation_link}}\n\nMohon konfirmasi kehadiran melalui:\n{{rsvp_link}}\n\n{{checkin_qr_hint}}\n\nTerima kasih.",
            ],
        ],
        'id_friendly' => [
            'label' => 'Indonesia Friendly',
            'carbon_locale' => 'id',
            'ui' => [
                'hero_kicker' => 'Cerita bahagia kami',
                'guest_label_personal' => 'Untuk Sahabat Kami',
                'guest_label_general' => 'Undangan Umum',
                'guest_name_fallback' => 'Teman dan keluarga',
                'guest_intro_personal' => 'Terima kasih sudah menerima undangan personal ini. Kami senang sekali kalau kamu bisa hadir dan ikut merayakan hari bahagia kami.',
                'guest_intro_general' => 'Silakan bagikan undangan umum ini kepada orang-orang terdekat yang ingin ikut berbahagia bersama kami.',
                'status_label' => 'Status',
                'main_date_label' => 'Tanggal utama',
                'countdown_label' => 'Hitung mundur menuju hari bahagia',
                'countdown_units' => ['Hari', 'Jam', 'Menit', 'Detik'],
                'couple_label' => 'Tentang kami',
                'schedule_label' => 'Jadwal dan lokasi',
                'album_label' => 'Album',
                'rsvp_label' => 'RSVP',
                'rsvp_title' => 'Kabari kehadiranmu, ya.',
                'rsvp_name_placeholder' => 'Nama kamu',
                'rsvp_phone_placeholder' => 'Nomor WhatsApp',
                'rsvp_message_placeholder' => 'Pesan singkat atau doa',
                'rsvp_submit' => 'Kirim RSVP',
                'music_label' => 'Backsound',
                'music_title' => 'Putar musik undangan.',
                'gift_label' => 'Hadiah',
                'gift_title' => 'Kalau ingin mengirim hadiah.',
                'gift_confirm' => 'Konfirmasi hadiah',
                'comments_label' => 'Ucapan',
                'comments_title' => 'Tinggalkan ucapan terbaikmu.',
                'comments_name_placeholder' => 'Nama kamu',
                'comments_message_placeholder' => 'Tulis ucapan',
                'comments_submit' => 'Kirim ucapan',
                'comments_empty' => 'Ucapan akan tampil di sini setelah dikirim.',
                'qr_label' => 'QR Check-in',
                'qr_title' => 'Simpan akses tamu untuk hari-H.',
                'qr_note' => 'QR ini tetap aman dan tidak memuat data pribadi.',
                'closing_label' => 'Penutup',
                'closing_title' => 'Sampai ketemu di hari istimewa kami.',
                'map_button' => 'Lihat Maps',
                'rsvp_status_labels' => [
                    'hadir' => 'Hadir',
                    'tidak_hadir' => 'Belum bisa hadir',
                    'ragu' => 'Masih tentatif',
                ],
            ],
            'defaults' => [
                'opening_text' => 'Dengan bahagia, kami mengundang Anda untuk hadir di hari istimewa kami dan merayakan momen ini bersama keluarga serta sahabat terdekat.',
                'invitation_text' => 'Kehadiran, doa, dan ucapan hangat dari Anda akan menjadi bagian berharga dalam hari bahagia kami.',
                'closing_text' => 'Terima kasih sudah meluangkan waktu untuk membuka undangan ini. Semoga kita bisa bertemu langsung di hari istimewa nanti.',
                'no_gift_message' => 'Kami tidak mengharapkan hadiah apa pun. Kehadiran dan doa terbaik Anda sudah menjadi hadiah yang sangat berarti.',
                'gift_instructions' => 'Jika ingin mengirim hadiah, Anda dapat menggunakan informasi berikut. Terima kasih atas perhatian dan kebaikannya.',
                'broadcast_template' => "Halo {{guest_name}},\nKami ingin mengundang kamu untuk hadir di acara {{couple_names}} pada {{event_date}}.\n\nBuka undangannya di sini:\n{{invitation_link}}\n\nKalau sempat, mohon isi RSVP juga ya:\n{{rsvp_link}}\n\n{{checkin_qr_hint}}\n\nTerima kasih.",
            ],
        ],
        'en' => [
            'label' => 'English',
            'carbon_locale' => 'en',
            'ui' => [
                'hero_kicker' => 'Wedding invitation',
                'guest_label_personal' => 'Dear',
                'guest_label_general' => 'General Invitation',
                'guest_name_fallback' => 'Family and Friends',
                'guest_intro_personal' => 'Thank you for receiving this personal invitation. It would mean a lot to us if you could join us and share your blessings on our special day.',
                'guest_intro_general' => 'Please share this general invitation with the family, friends, or colleagues who are relevant to the celebration.',
                'status_label' => 'Status',
                'main_date_label' => 'Main date',
                'countdown_label' => 'Countdown to our special day',
                'countdown_units' => ['Days', 'Hours', 'Minutes', 'Seconds'],
                'couple_label' => 'The couple',
                'schedule_label' => 'Schedule and venue',
                'album_label' => 'Album',
                'rsvp_label' => 'RSVP',
                'rsvp_title' => 'Please confirm your attendance.',
                'rsvp_name_placeholder' => 'Your name',
                'rsvp_phone_placeholder' => 'WhatsApp number',
                'rsvp_message_placeholder' => 'Message or note',
                'rsvp_submit' => 'Submit RSVP',
                'music_label' => 'Music',
                'music_title' => 'Play the invitation soundtrack.',
                'gift_label' => 'Gifting',
                'gift_title' => 'Gift options for you.',
                'gift_confirm' => 'Confirm gift',
                'comments_label' => 'Wishes',
                'comments_title' => 'Leave your kind wishes for the couple.',
                'comments_name_placeholder' => 'Your name',
                'comments_message_placeholder' => 'Write your wishes',
                'comments_submit' => 'Send wishes',
                'comments_empty' => 'No wishes have been displayed yet.',
                'qr_label' => 'Check-in QR',
                'qr_title' => 'Keep your guest access ready for the wedding day.',
                'qr_note' => 'This QR payload does not include private data.',
                'closing_label' => 'Closing',
                'closing_title' => 'We look forward to seeing you on our special day.',
                'map_button' => 'Open Maps',
                'rsvp_status_labels' => [
                    'hadir' => 'Attending',
                    'tidak_hadir' => 'Unable to attend',
                    'ragu' => 'Maybe',
                ],
            ],
            'defaults' => [
                'opening_text' => 'By the grace of God, we warmly invite you to celebrate our wedding day with us.',
                'invitation_text' => 'Your presence, prayers, and kind wishes would be a wonderful gift as we begin this new chapter together.',
                'closing_text' => 'Thank you for your time, love, and blessings. We hope to celebrate with you in person.',
                'no_gift_message' => 'With sincere gratitude, we kindly request no gifts. Your presence and blessings are more than enough for us.',
                'gift_instructions' => 'Your prayers are already a precious gift. If you would still like to send a gift, you may use the information below.',
                'broadcast_template' => "Dear {{guest_name}},\nWe are delighted to invite you to celebrate the wedding of {{couple_names}} on {{event_date}}.\n\nPlease open the invitation here:\n{{invitation_link}}\n\nKindly confirm your attendance through:\n{{rsvp_link}}\n\n{{checkin_qr_hint}}\n\nThank you.",
            ],
        ],
        'jv' => [
            'label' => 'Jawa Halus',
            'carbon_locale' => 'id',
            'ui' => [
                'hero_kicker' => 'Undangan pawiwahan',
                'guest_label_personal' => 'Kagem',
                'guest_label_general' => 'Undangan Umum',
                'guest_name_fallback' => 'Bapak/Ibu/Sedherek',
                'guest_intro_personal' => 'Matur nuwun sampun kersa mirsani undangan pribadi menika. Mugi panjenengan kersa rawuh saha maringi pangestu ing dinten bingah kula.',
                'guest_intro_general' => 'Monggo dipun sebarke dhateng kulawarga lan kanca ingkang prayogi.',
                'status_label' => 'Status',
                'main_date_label' => 'Dinten utama',
                'countdown_label' => 'Wektu tumuju dinten bingah',
                'countdown_units' => ['Dinten', 'Jam', 'Menit', 'Detik'],
                'couple_label' => 'Penganten',
                'schedule_label' => 'Jadwal lan papan',
                'album_label' => 'Album',
                'rsvp_label' => 'RSVP',
                'rsvp_title' => 'Nyuwun konfirmasi rawuh panjenengan.',
                'rsvp_name_placeholder' => 'Asma panjenengan',
                'rsvp_phone_placeholder' => 'Nomor WhatsApp',
                'rsvp_message_placeholder' => 'Pesen utawi pangestu',
                'rsvp_submit' => 'Kirim RSVP',
                'music_label' => 'Backsound',
                'music_title' => 'Putar swasana undangan.',
                'gift_label' => 'Hadiah',
                'gift_title' => 'Pilihan bingkisan kangge panjenengan.',
                'gift_confirm' => 'Konfirmasi hadiah',
                'comments_label' => 'Ucapan',
                'comments_title' => 'Monggo paring ucapan lan pangestu.',
                'comments_name_placeholder' => 'Asma panjenengan',
                'comments_message_placeholder' => 'Tulis ucapan',
                'comments_submit' => 'Kirim ucapan',
                'comments_empty' => 'Dereng wonten ucapan ingkang katampil.',
                'qr_label' => 'QR Check-in',
                'qr_title' => 'Siyapaken akses tamu kangge dinten-H.',
                'qr_note' => 'QR menika boten ngemot data pribadi.',
                'closing_label' => 'Panutup',
                'closing_title' => 'Ngantos ketemu ing dinten bingah kula.',
                'map_button' => 'Bukak Maps',
                'rsvp_status_labels' => [
                    'hadir' => 'Rawuh',
                    'tidak_hadir' => 'Mboten saged rawuh',
                    'ragu' => 'Dereng mesthi',
                ],
            ],
            'defaults' => [
                'opening_text' => 'Kanthi nyuwun sih rahmat saha ridho Gusti Allah, kula nyuwun pakurmatan panjenengan rawuh ing pawiwahan menika.',
                'invitation_text' => 'Rawuhipun panjenengan saha pangestu ingkang pinaringan badhe dados kabungahan ing dinten istimewa kula.',
                'closing_text' => 'Matur nuwun sanget awit saking rawuh saha pangestunipun panjenengan.',
                'no_gift_message' => 'Kanthi andhap asor, kula boten nampi bingkisan. Rawuh saha pangestunipun panjenengan sampun langkung saking cekap.',
                'gift_instructions' => 'Pangestu panjenengan sampun dados bingkisan ingkang pinunjul. Menawi kersa maringi bingkisan, saged migunakaken informasi menika.',
                'broadcast_template' => "Kagem {{guest_name}},\nKanthi suka bingah kula ngaturaken undangan pawiwahan {{couple_names}} ing {{event_date}}.\n\nMonggo mirsani undanganipun wonten mriki:\n{{invitation_link}}\n\nNyuwun konfirmasi rawuhipun wonten:\n{{rsvp_link}}\n\n{{checkin_qr_hint}}\n\nMatur nuwun.",
            ],
        ],
    ],
];
